"""empty message

Revision ID: 28c9887f09ce
Revises: 8ce8dfafb3a7
Create Date: 2017-11-15 19:50:40.531961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28c9887f09ce'
down_revision = '8ce8dfafb3a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('content', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'content')
    # ### end Alembic commands ###
