"""empty message

Revision ID: 6ed86f7fdc28
Revises: 28c9887f09ce
Create Date: 2017-11-20 15:05:29.644868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ed86f7fdc28'
down_revision = '28c9887f09ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('father_answer_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'father_answer_id')
    # ### end Alembic commands ###
