"""empty message

Revision ID: 8ce8dfafb3a7
Revises: cdba3d4d42af
Create Date: 2017-11-15 15:24:41.582487

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ce8dfafb3a7'
down_revision = 'cdba3d4d42af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plate', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.drop_constraint('plate_ibfk_1', 'plate', type_='foreignkey')
    op.drop_column('plate', 'father_id')
    op.drop_column('plate', 'author_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plate', sa.Column('author_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('plate', sa.Column('father_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('plate_ibfk_1', 'plate', 'user', ['author_id'], ['id'])
    op.drop_column('plate', 'create_time')
    # ### end Alembic commands ###
